using System;
using System.Linq;

namespace WhileTrue.Classes.ATR
{
    public class Country
    {
        public string A2Code { get; set; }
        public string A3Code { get; set; }
        public string NumberCode { get; set; }
        public string Name { get; set; }

        static Country()
        {
            Country.Countries = new[]
            {
                new Country("AD", "AND", "020", "ANDORRA"),
                new Country("AE", "ARE", "784", "UNITED ARAB EMIRATES"),
                new Country("AF", "AFG", "004", "AFGHANISTAN"),
                new Country("AG", "ATG", "028", "ANTIGUA AND BARBUDA"),
                new Country("AI", "AIA", "660", "ANGUILLA"),
                new Country("AL", "ALB", "008", "ALBANIA"),
                new Country("AM", "ARM", "051", "ARMENIA"),
                new Country("AN", "ANT", "530", "NETHERLANDS ANTILLES"),
                new Country("AO", "AGO", "024", "ANGOLA"),
                new Country("AQ", "ATA", "010", "ANTARCTICA"),
                new Country("AR", "ARG", "032", "ARGENTINA"),
                new Country("AS", "ASM", "016", "AMERICAN SAMOA"),
                new Country("AT", "AUT", "040", "AUSTRIA"),
                new Country("AU", "AUS", "036", "AUSTRALIA"),
                new Country("AW", "ABW", "533", "ARUBA"),
                new Country("AZ", "AZE", "031", "AZERBAIJAN"),
                new Country("BA", "BIH", "070", "BOSNIA AND HERZEGOWINA"),
                new Country("BB", "BRB", "052", "BARBADOS"),
                new Country("BD", "BGD", "050", "BANGLADESH"),
                new Country("BE", "BEL", "056", "BELGIUM"),
                new Country("BF", "BFA", "854", "BURKINA FASO"),
                new Country("BG", "BGR", "100", "BULGARIA"),
                new Country("BH", "BHR", "048", "BAHRAIN"),
                new Country("BI", "BDI", "108", "BURUNDI"),
                new Country("BJ", "BEN", "204", "BENIN"),
                new Country("BM", "BMU", "060", "BERMUDA"),
                new Country("BN", "BRN", "096", "BRUNEI DARUSSALAM"),
                new Country("BO", "BOL", "068", "BOLIVIA"),
                new Country("BR", "BRA", "076", "BRAZIL"),
                new Country("BS", "BHS", "044", "BAHAMAS"),
                new Country("BT", "BTN", "064", "BHUTAN"),
                new Country("BV", "BVT", "074", "BOUVET ISLAND"),
                new Country("BW", "BWA", "072", "BOTSWANA"),
                new Country("BY", "BLR", "112", "BELARUS"),
                new Country("BZ", "BLZ", "084", "BELIZE"),
                new Country("CA", "CAN", "124", "CANADA"),
                new Country("CC", "CCK", "166", "COCOS (KEELING) ISLANDS"),
                new Country("CF", "CAF", "140", "CENTRAL AFRICAN REPUBLIC"),
                new Country("CG", "COG", "178", "CONGO"),
                new Country("CH", "CHE", "756", "SWITZERLAND"),
                new Country("CI", "CIV", "384", "COTE D'IVOIRE"),
                new Country("CK", "COK", "184", "COOK ISLANDS"),
                new Country("CL", "CHL", "152", "CHILE"),
                new Country("CM", "CMR", "120", "CAMEROON"),
                new Country("CN", "CHN", "156", "CHINA"),
                new Country("CO", "COL", "170", "COLOMBIA"),
                new Country("CR", "CRI", "188", "COSTA RICA"),
                new Country("CU", "CUB", "192", "CUBA"),
                new Country("CV", "CPV", "132", "CAPE VERDE"),
                new Country("CX", "CXR", "162", "CHRISTMAS ISLAND"),
                new Country("CY", "CYP", "196", "CYPRUS"),
                new Country("CZ", "CZE", "203", "CZECH REPUBLIC"),
                new Country("DE", "DEU", "276", "GERMANY"),
                new Country("DJ", "DJI", "262", "DJIBOUTI"),
                new Country("DK", "DNK", "208", "DENMARK"),
                new Country("DM", "DMA", "212", "DOMINICA"),
                new Country("DO", "DOM", "214", "DOMINICAN REPUBLIC"),
                new Country("DZ", "DZA", "012", "ALGERIA"),
                new Country("EC", "ECU", "218", "ECUADOR"),
                new Country("EE", "EST", "233", "ESTONIA"),
                new Country("EG", "EGY", "818", "EGYPT"),
                new Country("EH", "ESH", "732", "WESTERN SAHARA"),
                new Country("ER", "ERI", "232", "ERITREA"),
                new Country("ES", "ESP", "724", "SPAIN"),
                new Country("ET", "ETH", "231", "ETHIOPIA"),
                new Country("FI", "FIN", "246", "FINLAND"),
                new Country("FJ", "FJI", "242", "FIJI"),
                new Country("FK", "FLK", "238", "FALKLAND ISLANDS (MALVINAS)"),
                new Country("FM", "FSM", "583", "MICRONESIA, FEDERATED STATES OF"),
                new Country("FO", "FRO", "234", "FAROE ISLANDS"),
                new Country("FR", "FRA", "250", "FRANCE"),
                new Country("FX", "FXX", "249", "FRANCE, METROPOLITAN"),
                new Country("GA", "GAB", "266", "GABON"),
                new Country("GB", "GBR", "826", "UNITED KINGDOM"),
                new Country("GD", "GRD", "308", "GRENADA"),
                new Country("GE", "GEO", "268", "GEORGIA"),
                new Country("GF", "GUF", "254", "FRENCH GUIANA"),
                new Country("GH", "GHA", "288", "GHANA"),
                new Country("GI", "GIB", "292", "GIBRALTAR"),
                new Country("GL", "GRL", "304", "GREENLAND"),
                new Country("GM", "GMB", "270", "GAMBIA"),
                new Country("GN", "GIN", "324", "GUINEA"),
                new Country("GP", "GLP", "312", "GUADELOUPE"),
                new Country("GQ", "GNQ", "226", "EQUATORIAL GUINEA"),
                new Country("GR", "GRC", "300", "GREECE"),
                new Country("GS", "SGS", "239", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"),
                new Country("GT", "GTM", "320", "GUATEMALA"),
                new Country("GU", "GUM", "316", "GUAM"),
                new Country("GW", "GNB", "624", "GUINEA-BISSAU"),
                new Country("GY", "GUY", "328", "GUYANA"),
                new Country("HK", "HKG", "344", "HONG KONG"),
                new Country("HM", "HMD", "334", "HEARD AND MC DONALD ISLANDS"),
                new Country("HN", "HND", "340", "HONDURAS"),
                new Country("HR", "HRV", "191", "CROATIA (local name: Hrvatska)"),
                new Country("HT", "HTI", "332", "HAITI"),
                new Country("HU", "HUN", "348", "HUNGARY"),
                new Country("ID", "IDN", "360", "INDONESIA"),
                new Country("IE", "IRL", "372", "IRELAND"),
                new Country("IL", "ISR", "376", "ISRAEL"),
                new Country("IN", "IND", "356", "INDIA"),
                new Country("IO", "IOT", "086", "BRITISH INDIAN OCEAN TERRITORY"),
                new Country("IQ", "IRQ", "368", "IRAQ"),
                new Country("IR", "IRN", "364", "IRAN (ISLAMIC REPUBLIC OF)"),
                new Country("IS", "ISL", "352", "ICELAND"),
                new Country("IT", "ITA", "380", "ITALY"),
                new Country("JM", "JAM", "388", "JAMAICA"),
                new Country("JO", "JOR", "400", "JORDAN"),
                new Country("JP", "JPN", "392", "JAPAN"),
                new Country("KE", "KEN", "404", "KENYA"),
                new Country("KG", "KGZ", "417", "KYRGYZSTAN"),
                new Country("KH", "KHM", "116", "CAMBODIA"),
                new Country("KI", "KIR", "296", "KIRIBATI"),
                new Country("KM", "COM", "174", "COMOROS"),
                new Country("KN", "KNA", "659", "SAINT KITTS AND NEVIS"),
                new Country("KP", "PRK", "408", "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
                new Country("KR", "KOR", "410", "KOREA, REPUBLIC OF"),
                new Country("KW", "KWT", "414", "KUWAIT"),
                new Country("KY", "CYM", "136", "CAYMAN ISLANDS"),
                new Country("KZ", "KAZ", "398", "KAZAKHSTAN"),
                new Country("LA", "LAO", "418", "LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
                new Country("LB", "LBN", "422", "LEBANON"),
                new Country("LC", "LCA", "662", "SAINT LUCIA"),
                new Country("LI", "LIE", "438", "LIECHTENSTEIN"),
                new Country("LK", "LKA", "144", "SRI LANKA"),
                new Country("LR", "LBR", "430", "LIBERIA"),
                new Country("LS", "LSO", "426", "LESOTHO"),
                new Country("LT", "LTU", "440", "LITHUANIA"),
                new Country("LU", "LUX", "442", "LUXEMBOURG"),
                new Country("LV", "LVA", "428", "LATVIA"),
                new Country("LY", "LBY", "434", "LIBYAN ARAB JAMAHIRIYA"),
                new Country("MA", "MAR", "504", "MOROCCO"),
                new Country("MC", "MCO", "492", "MONACO"),
                new Country("MD", "MDA", "498", "MOLDOVA, REPUBLIC OF"),
                new Country("MG", "MDG", "450", "MADAGASCAR"),
                new Country("MH", "MHL", "584", "MARSHALL ISLANDS"),
                new Country("MK", "MKD", "807", "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"),
                new Country("ML", "MLI", "466", "MALI"),
                new Country("MM", "MMR", "104", "MYANMAR"),
                new Country("MN", "MNG", "496", "MONGOLIA"),
                new Country("MO", "MAC", "446", "MACAU"),
                new Country("MP", "MNP", "580", "NORTHERN MARIANA ISLANDS"),
                new Country("MQ", "MTQ", "474", "MARTINIQUE"),
                new Country("MR", "MRT", "478", "MAURITANIA"),
                new Country("MS", "MSR", "500", "MONTSERRAT"),
                new Country("MT", "MLT", "470", "MALTA"),
                new Country("MU", "MUS", "480", "MAURITIUS"),
                new Country("MV", "MDV", "462", "MALDIVES"),
                new Country("MW", "MWI", "454", "MALAWI"),
                new Country("MX", "MEX", "484", "MEXICO"),
                new Country("MY", "MYS", "458", "MALAYSIA"),
                new Country("MZ", "MOZ", "508", "MOZAMBIQUE"),
                new Country("NA", "NAM", "516", "NAMIBIA"),
                new Country("NC", "NCL", "540", "NEW CALEDONIA"),
                new Country("NE", "NER", "562", "NIGER"),
                new Country("NF", "NFK", "574", "NORFOLK ISLAND"),
                new Country("NG", "NGA", "566", "NIGERIA"),
                new Country("NI", "NIC", "558", "NICARAGUA"),
                new Country("NL", "NLD", "528", "NETHERLANDS"),
                new Country("NO", "NOR", "578", "NORWAY"),
                new Country("NP", "NPL", "524", "NEPAL"),
                new Country("NR", "NRU", "520", "NAURU"),
                new Country("NU", "NIU", "570", "NIUE"),
                new Country("NZ", "NZL", "554", "NEW ZEALAND"),
                new Country("OM", "OMN", "512", "OMAN"),
                new Country("PA", "PAN", "591", "PANAMA"),
                new Country("PE", "PER", "604", "PERU"),
                new Country("PF", "PYF", "258", "FRENCH POLYNESIA"),
                new Country("PG", "PNG", "598", "PAPUA NEW GUINEA"),
                new Country("PH", "PHL", "608", "PHILIPPINES"),
                new Country("PK", "PAK", "586", "PAKISTAN"),
                new Country("PL", "POL", "616", "POLAND"),
                new Country("PM", "SPM", "666", "ST. PIERRE AND MIQUELON"),
                new Country("PN", "PCN", "612", "PITCAIRN"),
                new Country("PR", "PRI", "630", "PUERTO RICO"),
                new Country("PT", "PRT", "620", "PORTUGAL"),
                new Country("PW", "PLW", "585", "PALAU"),
                new Country("PY", "PRY", "600", "PARAGUAY"),
                new Country("QA", "QAT", "634", "QATAR"),
                new Country("RE", "REU", "638", "REUNION"),
                new Country("RO", "ROM", "642", "ROMANIA"),
                new Country("RU", "RUS", "643", "RUSSIAN FEDERATION"),
                new Country("RW", "RWA", "646", "RWANDA"),
                new Country("SA", "SAU", "682", "SAUDI ARABIA"),
                new Country("SB", "SLB", "090", "SOLOMON ISLANDS"),
                new Country("SC", "SYC", "690", "SEYCHELLES"),
                new Country("SD", "SDN", "736", "SUDAN"),
                new Country("SE", "SWE", "752", "SWEDEN"),
                new Country("SG", "SGP", "702", "SINGAPORE"),
                new Country("SH", "SHN", "654", "ST. HELENA"),
                new Country("SI", "SVN", "705", "SLOVENIA"),
                new Country("SJ", "SJM", "744", "SVALBARD AND JAN MAYEN ISLANDS"),
                new Country("SK", "SVK", "703", "SLOVAKIA (Slovak Republic)"),
                new Country("SL", "SLE", "694", "SIERRA LEONE"),
                new Country("SM", "SMR", "674", "SAN MARINO"),
                new Country("SN", "SEN", "686", "SENEGAL"),
                new Country("SO", "SOM", "706", "SOMALIA"),
                new Country("SR", "SUR", "740", "SURINAME"),
                new Country("ST", "STP", "678", "SAO TOME AND PRINCIPE"),
                new Country("SV", "SLV", "222", "EL SALVADOR"),
                new Country("SY", "SYR", "760", "SYRIAN ARAB REPUBLIC"),
                new Country("SZ", "SWZ", "748", "SWAZILAND"),
                new Country("TC", "TCA", "796", "TURKS AND CAICOS ISLANDS"),
                new Country("TD", "TCD", "148", "CHAD"),
                new Country("TF", "ATF", "260", "FRENCH SOUTHERN TERRITORIES"),
                new Country("TG", "TGO", "768", "TOGO"),
                new Country("TH", "THA", "764", "THAILAND"),
                new Country("TJ", "TJK", "762", "TAJIKISTAN"),
                new Country("TK", "TKL", "772", "TOKELAU"),
                new Country("TM", "TKM", "795", "TURKMENISTAN"),
                new Country("TN", "TUN", "788", "TUNISIA"),
                new Country("TO", "TON", "776", "TONGA"),
                new Country("TP", "TMP", "626", "EAST TIMOR"),
                new Country("TR", "TUR", "792", "TURKEY"),
                new Country("TT", "TTO", "780", "TRINIDAD AND TOBAGO"),
                new Country("TV", "TUV", "798", "TUVALU"),
                new Country("TW", "TWN", "158", "TAIWAN, PROVINCE OF CHINA"),
                new Country("TZ", "TZA", "834", "TANZANIA, UNITED REPUBLIC OF"),
                new Country("UA", "UKR", "804", "UKRAINE"),
                new Country("UG", "UGA", "800", "UGANDA"),
                new Country("UM", "UMI", "581", "UNITED STATES MINOR OUTLYING ISLANDS"),
                new Country("US", "USA", "840", "UNITED STATES"),
                new Country("UY", "URY", "858", "URUGUAY"),
                new Country("UZ", "UZB", "860", "UZBEKISTAN"),
                new Country("VA", "VAT", "336", "VATICAN CITY STATE (HOLY SEE)"),
                new Country("VC", "VCT", "670", "SAINT VINCENT AND THE GRENADINES"),
                new Country("VE", "VEN", "862", "VENEZUELA"),
                new Country("VG", "VGB", "092", "VIRGIN ISLANDS (BRITISH)"),
                new Country("VI", "VIR", "850", "VIRGIN ISLANDS (U.S.)"),
                new Country("VN", "VNM", "704", "VIET NAM"),
                new Country("VU", "VUT", "548", "VANUATU"),
                new Country("WF", "WLF", "876", "WALLIS AND FUTUNA ISLANDS"),
                new Country("WS", "WSM", "882", "SAMOA"),
                new Country("YE", "YEM", "887", "YEMEN"),
                new Country("YT", "MYT", "175", "MAYOTTE"),
                new Country("YU", "YUG", "891", "YUGOSLAVIA"),
                new Country("ZA", "ZAF", "710", "SOUTH AFRICA"),
                new Country("ZM", "ZMB", "894", "ZAMBIA"),
                new Country("ZR", "ZAR", "180", "ZAIRE"),
                new Country("ZW", "ZWE", "716", "ZIMBABWE")
            };
        }

        public static readonly Country[] Countries;

        private Country(string a2Code, string a3Code, string numberCode, string name)
        {
            this.A2Code = a2Code;
            this.A3Code = a3Code;
            this.NumberCode = numberCode;
            this.Name = name;
        }

        public static Country GetFromNumberCode(string numberCode)
        {
            if (numberCode.ToUpper().Trim('0', '1', '2', '3', '4', '5', '6', '7', '8', '9').Length == 0)
            {
                if (numberCode.Length == 3)
                {
                    numberCode = numberCode.ToUpper();
                    return Country.Countries.FirstOrDefault(_ => _.NumberCode == numberCode)??new Country(null,null,numberCode,"[unknown country]");
                }
                else
                {
                    throw new ArgumentException("country code must have 3 decimal digits, including leading zeros");
                }
            }
            else
            {
                throw new ArgumentException("only hex digits are allowed");
            }
        }

        public override string ToString()
        {
            return $"{this.Name} ({string.Join("/", new[] {this.A2Code, this.A3Code, this.NumberCode}.Where(_ => _ != null))})";
        }
    }
}